---
sidebar: sidebar
permalink: task-view-e-series.html
keywords: e-series, cluster, view, volumes, hosts, management ip, serial number, system id, capacity, allocated capacity
summary: After you discover your E-Series systems, you can view details about capacity distribution, volumes, and hosts.
---

= View your E-Series systems
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After you discover your E-Series systems, you can view details about capacity distribution, volumes, and hosts.

.Required NetApp Console role
Organization admin, Folder or project admin, Storage admin, or System health specialist. link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html[Learn about Console access roles.^]

.Steps

. From the navigation menu, select *Storage > Management*.

. On the *Systems* page, select the E-Series system that you want to view.

. Select any of available menu options to view more details about your E-Series system:
+
* *Overview*: A detailed view of the system's capacity distribution (allocated, free, and unassigned capacity), the number of volumes, hosts, and more.

* *Volumes*: Details about the volumes on the system, including assignment, RAID level, allocated capacity, and more.

* *Hosts*: Details about the hosts that send I/O to a volume on the storage system.

